language: python

stages:
  - verify
  - test

matrix:
  include:
    # This step comes first, as a fast validation that the code compiles
    - stage: verify
      python: 3.4
      script: python3 -m compileall -q .
      cache: false
      install: false
      dist: xenial
      sudo: required
    # Now all remaining steps
    - stage: test
      python: 2.7
    - stage: test
      python: 3.4
    - stage: test
      python: 3.5
    - stage: test
      python: 3.6
    - stage: test
      python: pypy
    # See https://github.com/travis-ci/travis-ci/issues/9815
    - stage: test
      python: 3.7
      dist: xenial
      sudo: required
    - stage: test
      python: pypy3.5
      dist: xenial
      sudo: required

# The following ends up being common for all jobs above.
# command to install dependencies
install:
    - pip install tox

script:
    - printf "[build_ext]\nportage-ext-modules=true" >> setup.cfg
    - |
      echo -en "travis_fold:start:setup.py_test\r"
      ./setup.py test
      echo -en "travis_fold:end:setup.py_test"
    - |
      echo -en "travis_fold:start:setup.py_install\r"
      ./setup.py install --root=/tmp/install-root
      echo -en "travis_fold:end:setup.py_install\r"
    - |
      echo -en "travis_fold:start:tox\r"
      if [[ ${TRAVIS_PYTHON_VERSION} == ?.? ]]; then
        tox -e py${TRAVIS_PYTHON_VERSION/./};
      else
        tox -e ${TRAVIS_PYTHON_VERSION};
      fi
      echo -en "travis_fold:end:tox\r"
