language: python

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: pypy
    # See https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7
      dist: xenial
      sudo: required
    - python: pypy3.5
      dist: xenial
      sudo: required

# command to install dependencies
install:
    - pip install tox

script:
    - printf "[build_ext]\nportage-ext-modules=true" >> setup.cfg
    - |
      echo -en "travis_fold:start:setup.py_test\r"
      ./setup.py test
      echo -en "travis_fold:end:setup.py_test"
    - |
      echo -en "travis_fold:start:setup.py_install\r"
      ./setup.py install --root=/tmp/install-root
      echo -en "travis_fold:end:setup.py_install\r"
    - |
      echo -en "travis_fold:start:tox\r"
      if [[ ${TRAVIS_PYTHON_VERSION} == ?.? ]]; then
        tox -e py${TRAVIS_PYTHON_VERSION/./};
      else
        tox -e ${TRAVIS_PYTHON_VERSION};
      fi
      echo -en "travis_fold:end:tox\r"
